In [33]:
from utils_tools.model_inference.model_predict import main_predict
from datetime import date

#from utils_tools.model_storage.storage import load_last_model
import time
%load_ext autoreload
%autoreload 2
if __name__ == '__main__':
    
    #ori_date="time_out"
    ori_date="20250102"
    results_label_0,results_label_1, results_label_2, time_result_df, error_sn=main_predict(ori_date)
    #print(results_label_124)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

Processing files:   0%|          | 0/1 [00:00<?, ?it/s]

Processing files: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]

特征数据已保存为 ./data/tsfresh_feature/20250115_1536_test.parquet
sn shape: (5,)
Series: 'sn' [str]
[
	"TP40KBT000B230…
	"TP40KBT000B240…
	"TP40KBT000B231…
	"TP40KBT000B240…
	"TP40KBT000B231…
]
共多少 5

In [34]:
results_label_2

                     sn  label  proba_label_0  proba_label_1  proba_label_2
0  TP40KBT000B230331296      2       0.101099       0.025644       0.873257
1  TP40KBT000B240122064      2       0.124825       0.023871       0.851303
2  TP40KBT000B231107051      2       0.124825       0.023871       0.851303

In [20]:
results_label_1

Empty DataFrame
Columns: [sn, label, proba_label_0, proba_label_1, proba_label_2]
Index: []

In [35]:
from utils_tools.model_inference.model_predict import main_predict
from datetime import date

#from utils_tools.model_storage.storage import load_last_model
import time
%load_ext autoreload
%autoreload 2
if __name__ == '__main__':
    
    #ori_date="time_out"
    ori_date="20250102"
    results_label_0,results_label_1, results_label_2, time_result_df, error_sn=main_predict(ori_date)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

Processing files:  33%|███▎      | 1/3 [00:00<00:00,  7.77it/s]

特征数据已保存为 ./data/tsfresh_feature/20250115_1538_test.parquet

Processing files:  67%|██████▋   | 2/3 [00:00<00:00,  8.27it/s]

特征数据已保存为 ./data/tsfresh_feature/20250115_1538_test.parquet

Processing files: 100%|██████████| 3/3 [00:00<00:00,  5.24it/s]

特征数据已保存为 ./data/tsfresh_feature/20250115_1538_test.parquet
sn shape: (58,)
Series: 'sn' [str]
[
	"TP40KBT000B231…
	"TP40KBT000B231…
	"TP40KBT000B231…
	"TP40KBT000B231…
	"TP40KBT000B231…
	"TP40KBT000B231…
	"TP40KBT000B231…
	"TP40KBT000B240…
	"TP40KBT000B240…
	"TP40KBT000B240…
	"TP40KBT000B240…
	"TP40KBT000B240…
	…
	"TP40KBT000B240…
	"TP40KBT000B240…
	"TP40KBT000B240…
	"TP40KBT000B240…
	"TP40KBT000B240…
	"TP40KBT000B240…
	"TP40KBT000B240…
	"TP40KBT000B240…
	"TP40KBT000B240…
	"TP40KBT000B240…
	"TP40KBT000B240…
	"TP40KBT000B240…
	"TP40KBT000B240…
]
共多少 58

ValueError: too many values to unpack (expected 4)

In [15]:
results_label_124

                        sn  label     proba
0   TP36KBT000B24041611209      1  0.554722
1   TP30KBT000B24032107909      1  0.508756
2   TP30KBT000B24030804009      1  0.550817
3   TP36KBT000B24033017209      1  0.524363
4   TP30KBT000B24041618209      1  0.533245
5   TP36KBT000B24042706409      1  0.582036
6   TP30KBT000B24030204109      1  0.608565
7   TP30KBT000B24041306109      1  0.501153
8   TP36KBT000B24041214109      1  0.559815
9   TP36KBT000B24041611709      1  0.513670
10  TP30KBT000B24032111309      1  0.543040
11  TP30KBT000B24052719409      1  0.729964
12  TP30KBT000B24040719509      1  0.604134

In [8]:
results.to_csv(f"./output/predict_results_{new_date}.csv", index=False)

Empty DataFrame
Columns: [sn, label, proba]
Index: []

In [3]:
results_label_024.write_csv("1231.csv")

AttributeError: 'DataFrame' object has no attribute 'write_csv'

In [30]:
import polars as pl
results_label_124 = pl.DataFrame(results_label_124)

#all_df=pl.read_parquet('/home/franco/power/inverter1/inverter/code_v4/data/train/processed/dataset_ng/ng_data.parquet')
errror=pl.read_csv('/home/franco/power/inverter1/inverter/code_v4/error_sn1.csv')
filtered_all = results_label_124.filter(pl.col('sn').is_in(errror['sn'].to_list()))
print(filtered_all)

shape: (0, 3)
┌─────┬───────┬───────┐
│ sn  ┆ label ┆ proba │
│ --- ┆ ---   ┆ ---   │
│ str ┆ i64   ┆ f32   │
╞═════╪═══════╪═══════╡
└─────┴───────┴───────┘

In [20]:
import polars as pl

# 读取数据
all_df = pl.read_parquet('/home/franco/power/inverter1/inverter/code_v4/filtered_data.parquet')

# 筛选出特定的 sn
target_sn = 'TP33KBT000B231011002'
filtered_df = all_df.filter(pl.col('sn') == target_sn)

# 进一步筛选出 ds 为 20250101 的记录
filtered_ds_df = filtered_df.filter(pl.col('ds') == "20241231")  # 如果 ds 是字符串
# 如果 ds 是整数，可以写成：
# filtered_ds_df = filtered_df.filter(pl.col('ds') == 20250101)

# 输出筛选结果
print(filtered_ds_df)

shape: (126, 89)
┌─────────────┬─────────────┬───────┬───────┬───┬─────────────┬────────────┬────────────┬──────────┐
│ invertersn  ┆ temperature ┆ vpv1  ┆ vpv2  ┆ … ┆ powerfactor ┆ createtime ┆ sn         ┆ ds       │
│ ---         ┆ ---         ┆ ---   ┆ ---   ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---      │
│ str         ┆ f64         ┆ f64   ┆ f64   ┆   ┆ f64         ┆ str        ┆ str        ┆ str      │
╞═════════════╪═════════════╪═══════╪═══════╪═══╪═════════════╪════════════╪════════════╪══════════╡
│ TP33KBT000B ┆ -2.4        ┆ 539.8 ┆ 459.3 ┆ … ┆ 1.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 07:21:37   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 0.7         ┆ 703.8 ┆ 678.2 ┆ … ┆ 1.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 07:26:38   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 0.7         ┆ 703.8 ┆ 678.2 ┆ … ┆ 1.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 07:31:22   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 2.2         ┆ 622.7 ┆ 584.1 ┆ … ┆ 0.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 07:36:23   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 4.3         ┆ 638.1 ┆ 659.4 ┆ … ┆ 0.13        ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 07:41:22   ┆ B231011002 ┆          │
│ …           ┆ …           ┆ …     ┆ …     ┆ … ┆ …           ┆ …          ┆ …          ┆ …        │
│ TP33KBT000B ┆ 33.8        ┆ 607.0 ┆ 574.6 ┆ … ┆ -0.86       ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 17:27:06   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 33.3        ┆ 526.9 ┆ 625.9 ┆ … ┆ 0.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 17:32:06   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 32.7        ┆ 626.9 ┆ 556.6 ┆ … ┆ 0.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 17:37:06   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 32.1        ┆ 546.2 ┆ 540.3 ┆ … ┆ 0.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 17:42:07   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 31.4        ┆ 573.2 ┆ 548.0 ┆ … ┆ 0.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 17:47:07   ┆ B231011002 ┆          │
└─────────────┴─────────────┴───────┴───────┴───┴─────────────┴────────────┴────────────┴──────────┘

In [25]:
import polars as pl

# 读取数据
all_df = pl.read_parquet('/home/franco/power/inverter1/inverter/code_v4/data/train/processed/dataset_ng3/ng_data2.parquet')

# 筛选特定的 sn
target_sn = 'TP33KBT000B231011002'
filtered_df = all_df.filter(pl.col('sn') == target_sn)

# 筛选出 ds 为 20250101 的记录
#filtered_ds_df = filtered_df.filter(pl.col('ds') == "20250101")  # 如果 ds 是字符串

# 将 createtime 转换为 datetime 类型（如果尚未是 datetime）
if not filtered_ds_df.schema["createtime"] == pl.Datetime:
    filtered_ds_df = filtered_ds_df.with_columns(
        pl.col("createtime").str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S")
    )

# 筛选 createtime 为 2024-12-31 的记录（忽略时间部分，只看日期）
filtered_final_df = filtered_ds_df.filter(
    pl.col("createtime").dt.date() == pl.date(2024, 12, 31)
)

# 输出筛选结果
print(filtered_final_df)

shape: (126, 89)
┌─────────────┬─────────────┬───────┬───────┬───┬─────────────┬────────────┬────────────┬──────────┐
│ invertersn  ┆ temperature ┆ vpv1  ┆ vpv2  ┆ … ┆ powerfactor ┆ createtime ┆ sn         ┆ ds       │
│ ---         ┆ ---         ┆ ---   ┆ ---   ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---      │
│ str         ┆ f64         ┆ f64   ┆ f64   ┆   ┆ f64         ┆ datetime[μ ┆ str        ┆ str      │
│             ┆             ┆       ┆       ┆   ┆             ┆ s]         ┆            ┆          │
╞═════════════╪═════════════╪═══════╪═══════╪═══╪═════════════╪════════════╪════════════╪══════════╡
│ TP33KBT000B ┆ -2.4        ┆ 539.8 ┆ 459.3 ┆ … ┆ 1.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 07:21:37   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 0.7         ┆ 703.8 ┆ 678.2 ┆ … ┆ 1.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 07:26:38   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 0.7         ┆ 703.8 ┆ 678.2 ┆ … ┆ 1.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 07:31:22   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 2.2         ┆ 622.7 ┆ 584.1 ┆ … ┆ 0.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 07:36:23   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 4.3         ┆ 638.1 ┆ 659.4 ┆ … ┆ 0.13        ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 07:41:22   ┆ B231011002 ┆          │
│ …           ┆ …           ┆ …     ┆ …     ┆ … ┆ …           ┆ …          ┆ …          ┆ …        │
│ TP33KBT000B ┆ 33.8        ┆ 607.0 ┆ 574.6 ┆ … ┆ -0.86       ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 17:27:06   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 33.3        ┆ 526.9 ┆ 625.9 ┆ … ┆ 0.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 17:32:06   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 32.7        ┆ 626.9 ┆ 556.6 ┆ … ┆ 0.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 17:37:06   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 32.1        ┆ 546.2 ┆ 540.3 ┆ … ┆ 0.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 17:42:07   ┆ B231011002 ┆          │
│ TP33KBT000B ┆ 31.4        ┆ 573.2 ┆ 548.0 ┆ … ┆ 0.0         ┆ 2024-12-31 ┆ TP33KBT000 ┆ 20241231 │
│ 231011002   ┆             ┆       ┆       ┆   ┆             ┆ 17:47:07   ┆ B231011002 ┆          │
└─────────────┴─────────────┴───────┴───────┴───┴─────────────┴────────────┴────────────┴──────────┘

In [11]:
all_df

shape: (1_313_911, 81)
┌─────────────┬───────┬───────┬───────┬───┬───────┬───────┬───────┬───────────────────┐
│ temperature ┆ vac1  ┆ vac2  ┆ vac3  ┆ … ┆ ipv28 ┆ ipv29 ┆ ipv30 ┆ __index_level_0__ │
│ ---         ┆ ---   ┆ ---   ┆ ---   ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---               │
│ f64         ┆ f64   ┆ f64   ┆ f64   ┆   ┆ f64   ┆ f64   ┆ f64   ┆ i64               │
╞═════════════╪═══════╪═══════╪═══════╪═══╪═══════╪═══════╪═══════╪═══════════════════╡
│ 21.2        ┆ 234.9 ┆ 236.0 ┆ 236.3 ┆ … ┆ 0.0   ┆ 0.0   ┆ 0.0   ┆ 0                 │
│ 21.5        ┆ 235.2 ┆ 234.8 ┆ 236.4 ┆ … ┆ 0.0   ┆ 0.0   ┆ 0.0   ┆ 1                 │
│ 21.5        ┆ 234.1 ┆ 236.4 ┆ 236.4 ┆ … ┆ 0.0   ┆ 0.0   ┆ 0.0   ┆ 2                 │
│ 21.5        ┆ 234.3 ┆ 235.4 ┆ 236.1 ┆ … ┆ 0.0   ┆ 0.0   ┆ 0.0   ┆ 3                 │
│ 21.9        ┆ 233.3 ┆ 235.9 ┆ 236.3 ┆ … ┆ 0.0   ┆ 0.0   ┆ 0.0   ┆ 4                 │
│ …           ┆ …     ┆ …     ┆ …     ┆ … ┆ …     ┆ …     ┆ …     ┆ …                 │
│ 35.4        ┆ 0.2   ┆ 1.2   ┆ 0.2   ┆ … ┆ null  ┆ null  ┆ null  ┆ 1637831           │
│ 35.6        ┆ 0.2   ┆ 0.8   ┆ 0.2   ┆ … ┆ null  ┆ null  ┆ null  ┆ 1637832           │
│ 35.6        ┆ 0.1   ┆ 0.8   ┆ 0.2   ┆ … ┆ null  ┆ null  ┆ null  ┆ 1637833           │
│ 35.8        ┆ 0.0   ┆ 1.0   ┆ 0.1   ┆ … ┆ null  ┆ null  ┆ null  ┆ 1637834           │
│ 35.8        ┆ 0.3   ┆ 0.7   ┆ 0.3   ┆ … ┆ null  ┆ null  ┆ null  ┆ 1637835           │
└─────────────┴───────┴───────┴───────┴───┴───────┴───────┴───────┴───────────────────┘

In [8]:
print(len(results_label_124))

6

In [2]:
results_label_024

Empty DataFrame
Columns: [sn, label, proba]
Index: []

In [16]:
import pandas as pd
#results_label_024=pd.read_csv('/home/franco/power/inverter1/inverter/code_v4/other_error/error_sn_df_20241223.csv')
time_sn_df = pd.read_csv("/home/franco/power/inverter1/inverter/code_v4/data/data_sn/sn_result_data_20241223.csv")
merged_df = pd.merge(results_label_024, time_sn_df[['sn', 'time']], on='sn', how='left')
merged_df.to_csv('./some_data/result/eorr_other.csv')

In [15]:
import polars as pl

# 读取 Parquet 文件
stats_ok = pl.read_parquet('/home/franco/power/inverter1/inverter/code_v4/data/data_all/20250104_final_stats_test.parquet')

# 将 'sn' 列转换为字符串类型，并创建一个新的列 'sn_str' 以保留原始 'sn' 值
stats_ok = stats_ok.with_columns(
    pl.col("sn").cast(pl.Utf8).alias("sn_str")
)

# 提取 'sn_str' 列的前6个字符，并创建新的列 'sn_prefix'
stats_ok = stats_ok.with_columns(
    pl.col("sn_str").str.slice(0, 6).alias("sn_prefix")
)

# 方法一：使用 groupby 和 count，然后按 count 降序排序
prefix_counts = stats_ok.groupby("sn_prefix").agg(
    pl.count().alias("count")
).sort("count", descending=True)  # 使用 sort_by 并指定 descending

print("每个唯一前6字符的出现次数 (使用 groupby 和 sort_by):")
print(prefix_counts)

每个唯一前6字符的出现次数 (使用 groupby 和 sort_by):
shape: (10, 2)
┌───────────┬───────┐
│ sn_prefix ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ TP40KB    ┆ 3069  │
│ TP30KB    ┆ 2779  │
│ TP36KB    ┆ 2303  │
│ TP33KB    ┆ 1522  │
│ TP25KB    ┆ 779   │
│ TP20KB    ┆ 408   │
│ TP17KB    ┆ 318   │
│ TP15KB    ┆ 265   │
│ TP12KB    ┆ 259   │
│ TP10KB    ┆ 206   │
└───────────┴───────┘

/tmp/ipykernel_3169965/337430294.py:17: DeprecationWarning: `groupby` is deprecated. It has been renamed to `group_by`.
  prefix_counts = stats_ok.groupby("sn_prefix").agg(
/tmp/ipykernel_3169965/337430294.py:18: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
  pl.count().alias("count")